{
  "threat_severity": "Moderate",
  "public_date": "2019-11-28T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2019-19906 cyrus-sasl: denial of service in _sasl_add_string function",
    "id": "1791854",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1791854"
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "cwe": "CWE-400",
  "details": [
    "cyrus-sasl (aka Cyrus SASL) 2.1.27 has an out-of-bounds write leading to unauthenticated remote denial-of-service in OpenLDAP via a malformed LDAP packet. The OpenLDAP crash is ultimately caused by an off-by-one error in _sasl_add_string in common.c in cyrus-sasl."
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Out of support scope",
      "package_name": "cyrus-sasl",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "cyrus-sasl",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Will not fix",
      "package_name": "cyrus-sasl",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "cyrus-sasl",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat JBoss Enterprise Web Server 2",
      "fix_state": "Out of support scope",
      "package_name": "cyrus-sasl",
      "cpe": "cpe:/a:redhat:jboss_enterprise_web_server:2"
    }
  ],
  "name": "CVE-2019-19906"
}
