{
  "threat_severity": "Moderate",
  "public_date": "2020-01-21T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2019-20387 libsolv: out-of-bounds read in repodata_schema2id in repodata.c",
    "id": "1797072",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1797072"
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "cwe": "CWE-125",
  "details": [
    "repodata_schema2id in repodata.c in libsolv before 0.7.6 has a heap-based buffer over-read via a last schema whose length is less than the length of the input schema.",
    "An out-of-bounds read was discovered in Libsolv when the last schema has a length that is less than the length of the input schema. A remote attacker may abuse this flaw to crash an application that uses Libsolv."
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Will not fix",
      "package_name": "libsolv",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "libsolv",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Affected",
      "package_name": "libsolv",
      "cpe": "cpe:/a:redhat:network_satellite:6"
    },
    {
      "product_name": "Red Hat Update Infrastructure 3 for Cloud Providers",
      "fix_state": "Affected",
      "package_name": "libsolv",
      "cpe": "cpe:/a:redhat:rhui:3"
    }
  ],
  "upstream_fix": "libsolv 0.7.6",
  "name": "CVE-2019-20387"
}
