{
  "bugs": [
    {
      "priority": "low",
      "cf_last_closed": null,
      "assigned_to_detail": {
        "email": "security-response-team",
        "real_name": "Red Hat Product Security",
        "name": "security-response-team",
        "id": 164808
      },
      "blocks": [
        1852831
      ],
      "creator": "Marian Rehak",
      "last_change_time": "2020-07-08T10:24:52Z",
      "is_cc_accessible": true,
      "keywords": [
        "Security"
      ],
      "creator_detail": {
        "email": "mrehak",
        "real_name": "Marian Rehak",
        "name": "mrehak",
        "id": 434842
      },
      "cc": [
        "Bill Dettelback",
        "Charalampos Stratakis",
        "jschorr",
        "Sandro Mani",
        "Michal Minar",
        "Python Maintainers",
        "Tom McKay",
        "Tomas Orsava",
        "Tomas Smetana"
      ],
      "url": "",
      "assigned_to": "Red Hat Product Security",
      "groups": [],
      "see_also": [],
      "id": 1852820,
      "whiteboard": "",
      "creation_time": "2020-07-01T11:36:45Z",
      "qa_contact": "",
      "depends_on": [
        1852821,
        1852822,
        1854823
      ],
      "dupe_of": null,
      "docs_contact": "",
      "resolution": "",
      "classification": "Other",
      "alias": [
        "CVE-2020-10994"
      ],
      "cf_doc_type": "If docs needed, set a value",
      "op_sys": "Linux",
      "target_release": [
        "---"
      ],
      "status": "NEW",
      "cc_detail": [
        {
          "email": "bdettelb",
          "real_name": "Bill Dettelback",
          "name": "bdettelb",
          "id": 438079
        },
        {
          "email": "cstratak",
          "real_name": "Charalampos Stratakis",
          "name": "cstratak",
          "id": 391080
        },
        {
          "email": "jschorr",
          "real_name": "",
          "name": "jschorr",
          "id": 432508
        },
        {
          "email": "manisandro",
          "real_name": "Sandro Mani",
          "name": "manisandro",
          "id": 284867
        },
        {
          "email": "miminar",
          "real_name": "Michal Minar",
          "name": "miminar",
          "id": 327440
        },
        {
          "email": "python-maint",
          "real_name": "Python Maintainers",
          "name": "python-maint",
          "id": 350238
        },
        {
          "email": "tomckay",
          "real_name": "Tom McKay",
          "name": "tomckay",
          "id": 318057
        },
        {
          "email": "torsava",
          "real_name": "Tomas Orsava",
          "name": "torsava",
          "id": 392175
        },
        {
          "email": "tsmetana",
          "real_name": "Tomas Smetana",
          "name": "tsmetana",
          "id": 211662
        }
      ],
      "cf_clone_of": null,
      "summary": "CVE-2020-10994 python-pillow: multiple out-of-bounds reads via a crafted JP2 file",
      "is_open": true,
      "platform": "All",
      "severity": "low",
      "cf_environment": "",
      "version": [
        "unspecified"
      ],
      "deadline": null,
      "component": [
        "vulnerability"
      ],
      "cf_fixed_in": "python-pillow 7.1.0",
      "is_creator_accessible": true,
      "is_confirmed": true,
      "target_milestone": "---",
      "product": "Security Response",
      "cf_release_notes": "An out-of-bounds read flaw was discovered in python-pillow in the way JP2 images are parsed. An application that uses python-pillow to decode untrusted images may be vulnerable to this flaw, which can allow an attacker to read data."
    }
  ],
  "faults": []
}
